version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

workflows:
  jobs:
    build:
      docker:
        - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - run :
            name: Run Tests
            command: mvn test
        - codecov/upload:
            file: './coverage/clover.xml'
            token: 525993e2-2a8f-44d9-b5c2-9560676cbf18

