version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  RunTest:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            mvn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 525993e2-2a8f-44d9-b5c2-9560676cbf18

workflows:
  version: 2
  run-test:
    jobs:
      - RunTest