version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.1.2
  token: '525993e2-2a8f-44d9-b5c2-9560676cbf18'

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target

