version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  codecov: codecov/codecov@1.0.2

  workflows:
    maven_test:
      jobs:
        - maven/test:
            command: '-X verify'
        - codecov/upload:
            file: {{ coverage_report_filepath }}
            token: ${CODECOV_TOKEN}