version: 2.1

orbs:
  maven: circleci/maven@1.0.3
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    steps:
      - codecov/upload:
          file: {{ coverage_report_filepath }}
          token: 525993e2-2a8f-44d9-b5c2-9560676cbf18

  workflows:
    maven_test:
      jobs:
        - maven/test:
            command: '-X verify'